import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { companyB, carousel, sections, carousel_2, news } from "../data";
import Carousel from "../components/Carousel";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Work from "../components/Work";
import News from "../components/News";

const BlockInfo = ({ color, title }: any) => {
  return (
    <div style={{ borderTop: `6px solid ${color}`, width: "100%", position: "relative", fontFamily: "Roboto", display: "flex", justifyContent: "center" }}>
      <div style={{ textTransform: "uppercase", textAlign: "center", background: "#E7A300", width: "500px", padding: "24px 12px", fontSize: "30px", fontFamily: "Lato", fontWeight: 900, color: "white" }}>
        {title}
      </div>
    </div>
  )
}

const CompanyCard: any = ({ title, url }: any) => {
  const [onHover, setOnHover] = useState(false)
  return (
    <div onMouseEnter={() => setOnHover(true)} onMouseLeave={() => setOnHover(false)} style={{ height: "260px", width: "190px", background: "#e9e8e8", position: "relative", display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center" }}>
      <div style={{ position: "relative", height: "100px", width: "100px" }}>
        <Image src={url} alt="test" layout='fill' objectFit='contain' quality='100' />
      </div>
      <p style={{ color: "grey", fontSize: "16px", fontFamily: "lato", fontWeight: 400, textTransform: "uppercase" }}>{title}</p>
    </div>
  )
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ankama : Retrouvez tous nos jeux, séries, films animés, BDs, romans, Artbooks, figurines et goodies.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Dosis:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </Head>

      <div className={styles.root}>
        <Header />

        <Carousel data={carousel} hasInfo />

        <BlockInfo title="Notre Société" color="#E7A300" />

        <div style={{ display: "flex", gap: "24px", padding: "24px", justifyContent: "center", alignItems: "center" }}>
          {companyB.map(({ title, svg, id }) => <CompanyCard key={id} title={title} url={svg} />)}
        </div>

        <Carousel data={carousel_2} />

        <BlockInfo title="Nos Créations" color="#E7A300" />

        <div>
          {sections.map(({ id, title, color, description, img, buttonColor }, index) => <Work ctaOnly={index === 0} key={id} title={title} color={color} description={description} img={img} buttonColor={buttonColor} />)}
        </div>

        <BlockInfo title="Actualités" color="#E7A300" />

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, auto)", gap: "24px", padding: "24px", width: "auto", justifyContent: "center", alignContent: "space-between", alignItems: "start" }}>
          {news.map(({ id, preview, article, avatar, name }) => <News key={id} preview={preview} article={article} avatar={avatar} name={name} />)}
        </div>

        <Footer />
      </div>
    </>
  )
}

export default Home
